---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jjq.
--- DateTime: 2022/9/14 17:11
---


local cluster               = require "cluster"
local skynet                = require "skynet"

local cluster_conf     = {
    self_node = {
        address         = "127.0.0.1:1234",
        sender          = "cluster/sender_example",
    },
    __nowaiting         = true,
}

local CMD = {}

function CMD.resp(...)
    skynet.error("test_cluster_sender:resp",...)
    return ...
end

local function cluster_client()
    skynet.error("cluster_client:call resp",cluster.call("self_node","@test_cluster_sender","resp","hello world"))
    skynet.error("cluster_client:call_sender print",cluster.call_sender("self_node","print","sender_example test print"))
end

skynet.start(function()
    --服务端
    cluster.reload(cluster_conf)
    cluster.register("test_cluster_sender")
    cluster.open("self_node")

    --客户端协程
    skynet.fork(cluster_client)

    skynet.dispatch("lua", function(session, source, cmd, ...)
        local f = assert(CMD[cmd])
        skynet.ret(skynet.pack(f(...)))
    end)
end)
