---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jjq.
--- DateTime: 2022/9/14 16:22
---


local cluster_sender            = require "cluster.cluster_sender_base"
local skynet 		            = require "skynet"

--服务启动初始化调用
local function constructor()
    skynet.error("sender_example:constructor")
end

--socketchannel连接之前调用
local function req_load_balance(host,port)
    skynet.error(string.format("sender_example:req_load_balance------%s:%s", host , port))
    return host,port
end

--socketchannel连接之后首次调用
local function auth(sc)
    skynet.error("sender_example:auth")
end

local CMD = {}

--其他service调用
function CMD.print(...)
    skynet.error("sender_example:print",...)
    return ...
end

--启动服务
cluster_sender.start({
    constructor         = constructor,
    auth                = auth,
    CMD                 = CMD,
    req_load_balance    = req_load_balance,
},...)